import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { useSpring } from "@react-spring/core";
import { a } from "@react-spring/web";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: React.ReactNode;
};

const Layout = (props: Props) => {
  const [{ background, fill }, set] = useSpring(
    { background: "#f0f0f0", fill: "#202020" },
    []
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full w-full flex">{props.children}</div>
    </>
  );
};

export default Layout;
