import React from "react";
import Head from "next/head";
import { useSpring } from "@react-spring/core";
import { a } from "@react-spring/web";
import Link from "next/link";
import { AiFillCode } from "react-icons/ai";
import { useApp } from "@/states/app";
import { FiMenu } from "react-icons/fi";

type Props = {
  children: React.ReactNode;
};

const Layout = (props: Props) => {
  const { set, background, fill } = useApp();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a.div style={{ background }} className="w-full">
        <a.div
          style={{ background }}
          className="w-full flex items-center p-2 justify-between lg:px-10 lg:py-5 fixed z-20"
        >
          <div className="text-sm lg:text-3xl rounded">
            <AiFillCode className="w-10 h-10 lg:w-full lg:h-full" />
          </div>
          <div className="text-sm lg:text-3xl rounded block lg:hidden">
            <FiMenu className="w-10 h-10 lg:w-full lg:h-full" />
          </div>
          <div className="hidden lg:flex items-center gap-3 font-bold text-lg">
            <Link href="">About</Link>
            <Link href="">Work</Link>
            <Link href="">Contact</Link>
          </div>
        </a.div>
        <div className="pt-20 px-2"> {props.children}</div>
      </a.div>
    </>
  );
};

export default Layout;
